# yamllint disable rule:line-length
---
name: percy-test
description: Percy workflow tests
permissions:
  contents: read
  pull-requests: write
on: [push, workflow_call, workflow_dispatch]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  demo-percy-test-job:
    uses: ./.github/workflows/robot_steps.yaml
    with:
      workflow_description: "Percy workflow tests"
      workflow_name: ${{ github.workflow }}
    secrets: inherit