# yamllint disable rule:line-length
---
name: robot_common_steps
description: Steps common to most robot workflows
on:
  workflow_call:
    inputs:
      workflow_description:
        description: Description of the workflow
        type: string
        required: true
      workflow_name:
        description: Name of the workflow
        type: string
        required: true
      extra_pabot_options:
        description: >
          Extra pabot options, e.g. include Robot Test Tags to run
        type: string
        required: true
      parallelism:
        description: Number of tests to run in parallel
        type: string
        required: false
        default: 1
      ENV:
        description: Environment name
        type: string
        required: false
        default: demo_qa
      DOMAIN:
        description: Domain under test
        type: string
        required: false
        default: counterparthealth.io
      slack_channel:
        description: Slack channel to send notifications
        type: string
        required: false
        default: NONE
      enable_test_observability:
        description: Enable test metrics to be sent to BrowserStack Test Observability
        type: boolean
        required: false
        default: true
      enable_browser_stack:
        description: Boolean to enable to browserstack
        type: boolean
        required: false
        default: false
      percy_visual_tests:
        required: false
        type: boolean
        default: false
permissions:
  contents: read
  pull-requests: write

jobs:
  common_robot_tests_job:
    name: ${{ inputs.workflow_name }}
    runs-on: gha-runner-set-cph-qa-shared
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      BROWSERSTACK_BUILD_NAME: ${{ inputs.workflow_description }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      PERCY_PROJECT: "d1902a5f/ca-visual-regression-automate"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Robocop
        run: |
          pip3 install robotframework-robocop==5.2.0
          python3 -m robocop -t W .

      - name: Install setup-chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libglib2.0-0 libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 \
            libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev \
            libxss-dev libasound2 xvfb fonts-liberation libu2f-udev \
            xdg-utils

      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: false
          install-chromedriver: true

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install -r tests/requirements.txt
      - name: Install BrowserStack Test Observability
        if: ${{ inputs.enable_test_observability }}
        run: |
          pip3 install browserstack-sdk
      - name: Setup Browserstack
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          if [[ "${{ inputs.enable_browser_stack }}" == "true" ]]; then
            echo "BROWSERSTACK_ACCESS_KEY is set to: $BROWSERSTACK_ACCESS_KEY and ${{ secrets.BROWSERSTACK_ACCESS_KEY }}"
            wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
            unzip BrowserStackLocal-linux-x64.zip
            ./BrowserStackLocal --key "${BROWSERSTACK_ACCESS_KEY}" --daemon start --local-identifier compatibility_tests --force-local
            sleep 5
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Run Percy tests
        if: ${{ inputs.percy_visual_tests }}
        run: |
          export HEADLESS=False
          export PERCY_LOGLEVEL=debug
          export PERCY_DEBUG=*
          pwd
          npm install --save-dev @percy/cli
          ./node_modules/.bin/percy exec:start --verbose &
          set +e
          pabot --processes ${{ inputs.parallelism }} ${{ inputs.extra_pabot_options }} \
            --variable compatibility_tests_win_chrome:True \
            --variable ENV:${{ inputs.ENV }} \
            --variable DOMAIN:${{ inputs.DOMAIN }} \
            --outputdir ./pabot_results/chrome ./tests/test.robot &

          chrome_pid=$!

          pabot --processes ${{ inputs.parallelism }} ${{ inputs.extra_pabot_options }} \
            --variable compatibility_tests_win_firefox:True \
            --variable ENV:${{ inputs.ENV }} \
            --variable DOMAIN:${{ inputs.DOMAIN }} \
            --outputdir ./pabot_results/firefox ./tests/test.robot &

          firefox_pid=$!

          pabot --processes ${{ inputs.parallelism }} ${{ inputs.extra_pabot_options }} \
            --variable compatibility_tests_osx_safari:True \
            --variable ENV:${{ inputs.ENV }} \
            --variable DOMAIN:${{ inputs.DOMAIN }} \
            --outputdir ./pabot_results/safari ./tests/test.robot &
            
          safari_pid=$!

          wait $chrome_pid
          chrome_exit_code=$?
          wait $firefox_pid
          firefox_exit_code=$?
          wait $safari_pid
          safari_exit_code=$?
          set -e

          echo "Exit codes: chrome=$chrome_exit_code  firefox=$firefox_exit_code safari=$safari_exit_code"
          if [[ $chrome_exit_code -ne 0 || $firefox_exit_code -ne 0 || $safari_exit_code -ne 0 ]]; then
            echo "One or more tests failed. Failing the build."
            echo "chrome=$chrome_exit_code firefox=$firefox_exit_code safari=$safari_exit_code"
          fi

          ./node_modules/.bin/percy exec:stop

          echo "CommitID: ${{ github.sha }}"
          ./node_modules/.bin/percy build:wait \
            --project "$PERCY_PROJECT" \
            --commit "${{ github.sha }}" \
            --fail-on-changes
      - name: Run Robot tests
        if: ${{ !inputs.percy_visual_tests }}
        run: |
          export HEADLESS=True
          github_branch=$(git rev-parse --abbrev-ref HEAD)
          cmd="pabot --processes ${{ inputs.parallelism }} ${{ inputs.extra_pabot_options }} --variable DOMAIN:${{ inputs.DOMAIN }} ."
          # Only send test metrics if Test Observability is enabled and GitHub branch is master
          if ${{ inputs.enable_test_observability }} && [ "$github_branch" = "master" ]; then
            eval "browserstack-sdk $cmd"
          else
            eval "$cmd"
          fi
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: >
            ${{ inputs.workflow_name }}.run${{ github.run_number }}.attempt${{ github.run_attempt }}
          path: |
            log.html
            output.xml
            report.html
            .pabotsuitenames
            pabot_results/
